//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProgram
{
    using System;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    
    public partial class Veriler : INotifyPropertyChanged
    {
        private int _Id;public int Id { get{ return _Id;} set{if(_Id != value){_Id = value; OnPropertyChanged("Id");}}}
        private string _Ad;public string Ad { get{ return _Ad;} set{if(_Ad != value){_Ad = value; OnPropertyChanged("Ad");}}}
        private string _Soyad;public string Soyad { get{ return _Soyad;} set{if(_Soyad != value){_Soyad = value; OnPropertyChanged("Soyad");}}}
        private string _Adres;public string Adres { get{ return _Adres;} set{if(_Adres != value){_Adres = value; OnPropertyChanged("Adres");}}}
        private string _Sehir;public string Sehir { get{ return _Sehir;} set{if(_Sehir != value){_Sehir = value; OnPropertyChanged("Sehir");}}}
        private string _Telefon;public string Telefon { get{ return _Telefon;} set{if(_Telefon != value){_Telefon = value; OnPropertyChanged("Telefon");}}}
        private string _Aciklama;public string Aciklama { get{ return _Aciklama;} set{if(_Aciklama != value){_Aciklama = value; OnPropertyChanged("Aciklama");}}}
        private string _Dosya;public string Dosya { get{ return _Dosya;} set{if(_Dosya != value){_Dosya = value; OnPropertyChanged("Dosya");}}}
        private string _Resim;public string Resim { get{ return _Resim;} set{if(_Resim != value){_Resim = value; OnPropertyChanged("Resim");}}}
        private Nullable<System.DateTime> _KayıtTarihi;public Nullable<System.DateTime> KayıtTarihi { get{ return _KayıtTarihi;} set{if(_KayıtTarihi != value){_KayıtTarihi = value; OnPropertyChanged("KayıtTarihi");}}}
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
            {
                WhenPropertyChanged(e);
                PropertyChanged(this, e);
            }
        }
    
        partial void WhenPropertyChanged(PropertyChangedEventArgs e);
        #endregion
    }
}
